import{a as R,S as q,i as a}from"./assets/vendor-BNibzuFn.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))g(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&g(c)}).observe(document,{childList:!0,subtree:!0});function e(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function g(t){if(t.ep)return;t.ep=!0;const s=e(t);fetch(t.href,s)}})();const x=R.create({baseURL:"https://pixabay.com/api/",params:{key:"52882585-ee96caa2c42b0b1b8477a4a7b",image_type:"photo",orientation:"horizontal",safesearch:!0}}),f=15;async function m(r,o=1){try{return(await x.get("",{params:{q:r,page:o,per_page:f}})).data}catch(e){throw console.error("Error fetching images:",e),e}}const p=document.querySelector(".gallery"),h=document.querySelector(".loader"),y=document.querySelector(".load-more"),E=new q(".gallery a",{captionsData:"alt",captionDelay:250});function b(r){const o=r.map(e=>`
    <a href="${e.largeImageURL}" class="gallery-item">
      <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
      <div class="info">
        <p class="info-txt"><b>Likes:</b> ${e.likes}</p>
        <p class="info-txt"><b>Views:</b> ${e.views}</p>
        <p class="info-txt"><b>Comments:</b> ${e.comments}</p>
        <p class="info-txt"><b>Downloads:</b> ${e.downloads}</p>
      </div>
    </a>`).join("");p.insertAdjacentHTML("beforeend",o),E.refresh()}function P(){p.innerHTML=""}function L(){h.classList.add("visible")}function w(){h.classList.remove("visible")}function v(){y.classList.add("visible")}function n(){y.classList.remove("visible")}const $={galleryContainer:p,loadMoreBtn:y,loader:h},S=document.querySelector(".form"),M=S.querySelector("input[name='search-text']"),{loadMoreBtn:u,galleryContainer:B}=$;let d="",i=1,l=0;n();S.addEventListener("submit",C);u.addEventListener("click",O);async function C(r){r.preventDefault();const o=M.value.trim();if(!o){a.warning({title:"Warning",message:"Please enter a search term!",position:"topRight"});return}d=o,i=1,l=0,P(),n(),L();try{const e=await m(d,i);if(l=e.totalHits??0,!e.hits||e.hits.length===0){a.info({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}b(e.hits),i*f<l?v():(n(),a.info({title:"End",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(e){a.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"}),console.error(e)}finally{w()}}async function O(){n(),u.disabled=!0,i+=1,L();try{const r=await m(d,i);if(r.hits&&r.hits.length>0){b(r.hits);const o=B.querySelector(".gallery-item");if(o){const{height:e}=o.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}}i*f>=(r.totalHits??l)?(n(),a.info({title:"End",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):v()}catch(r){a.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"}),console.error(r)}finally{w(),u.disabled=!1}}
//# sourceMappingURL=index.js.map
