import{a as x,S as E,i as a}from"./assets/vendor-BNibzuFn.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))b(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&b(c)}).observe(document,{childList:!0,subtree:!0});function e(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function b(t){if(t.ep)return;t.ep=!0;const s=e(t);fetch(t.href,s)}})();const P=x.create({baseURL:"https://pixabay.com/api/",params:{key:"52882585-ee96caa2c42b0b1b8477a4a7b",image_type:"photo",orientation:"horizontal",safesearch:!0}}),p=15;async function w(r,o=1){try{return(await P.get("",{params:{q:r,page:o,per_page:p}})).data}catch(e){throw console.error("Error fetching images:",e),e}}const h=document.querySelector(".gallery"),y=document.querySelector(".loader"),m=document.querySelector(".load-more"),$=new E(".gallery a",{captionsData:"alt",captionDelay:250});function v(r){const o=r.map(e=>`
    <a href="${e.largeImageURL}" class="gallery-item">
      <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
      <div class="info">
        <p class="info-txt"><b>Likes:</b> ${e.likes}</p>
        <p class="info-txt"><b>Views:</b> ${e.views}</p>
        <p class="info-txt"><b>Comments:</b> ${e.comments}</p>
        <p class="info-txt"><b>Downloads:</b> ${e.downloads}</p>
      </div>
    </a>`).join("");h.insertAdjacentHTML("beforeend",o),$.refresh()}function B(){h.innerHTML=""}function S(){y.classList.add("visible")}function R(){y.classList.remove("visible")}function q(){m.classList.add("visible")}function n(){m.classList.remove("visible")}const M={galleryContainer:h,loadMoreBtn:m,loader:y},g=document.querySelector(".form"),d=g.querySelector("input[name='search-text']"),L=g.querySelector("button[type='submit']"),{loadMoreBtn:u,galleryContainer:C}=M;let f="",i=1,l=0;n();g.addEventListener("submit",O);u.addEventListener("click",H);async function O(r){r.preventDefault();const o=d.value.trim();if(!o){a.warning({title:"Warning",message:"Please enter a search term!",position:"topRight"});return}f=o,i=1,l=0,B(),n(),S(),L.disabled=!0,d.disabled=!0;try{const e=await w(f,i);if(l=e.totalHits??0,!e.hits||e.hits.length===0){a.info({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}v(e.hits),i*p<l?q():(n(),a.info({title:"End",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(e){a.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"}),console.error(e)}finally{R(),L.disabled=!1,d.disabled=!1}}async function H(){n(),u.disabled=!0,i+=1,S();try{const r=await w(f,i);if(r.hits&&r.hits.length>0){v(r.hits);const o=C.querySelector(".gallery-item");if(o){const{height:e}=o.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}}i*p>=(r.totalHits??l)?(n(),a.info({title:"End",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):q()}catch(r){a.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"}),console.error(r)}finally{R(),u.disabled=!1}}
//# sourceMappingURL=index.js.map
