import{a as S,S as R,i as n}from"./assets/vendor-BNibzuFn.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))g(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&g(l)}).observe(document,{childList:!0,subtree:!0});function e(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function g(t){if(t.ep)return;t.ep=!0;const s=e(t);fetch(t.href,s)}})();const q=S.create({baseURL:"https://pixabay.com/api/",params:{key:"52882585-ee96caa2c42b0b1b8477a4a7b",image_type:"photo",orientation:"horizontal",safesearch:!0}}),d=15;async function m(r,o=1){try{return(await q.get("",{params:{q:r,page:o,per_page:d}})).data}catch(e){throw console.error("Error fetching images:",e),e}}const f=document.querySelector(".gallery"),p=document.querySelector(".loader"),h=document.querySelector(".load-more"),x=new R(".gallery a",{captionsData:"alt",captionDelay:250});function b(r){const o=r.map(e=>`
    <a href="${e.largeImageURL}" class="gallery-item">
      <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
      <div class="info">
        <p class="info-txt"><b>Likes:</b> ${e.likes}</p>
        <p class="info-txt"><b>Views:</b> ${e.views}</p>
        <p class="info-txt"><b>Comments:</b> ${e.comments}</p>
        <p class="info-txt"><b>Downloads:</b> ${e.downloads}</p>
      </div>
    </a>`).join("");f.insertAdjacentHTML("beforeend",o),x.refresh()}function E(){f.innerHTML=""}function L(){p.classList.add("visible")}function w(){p.classList.remove("visible")}function v(){h.classList.add("visible")}function c(){h.classList.remove("visible")}const P={galleryContainer:f,loadMoreBtn:h,loader:p},y=document.querySelector(".form"),$=y.querySelector("input[name='search-text']"),{loadMoreBtn:M,galleryContainer:B}=P;let u="",a=1,i=0;y.addEventListener("submit",C);M.addEventListener("click",O);async function C(r){r.preventDefault();const o=$.value.trim();if(!o){n.warning({title:"Warning",message:"Please enter a search term!",position:"topRight"});return}u=o,a=1,i=0,E(),c(),L();try{const e=await m(u,a);if(i=e.totalHits??0,!e.hits||e.hits.length===0){n.info({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}b(e.hits),a*d<i?v():(c(),n.info({title:"End",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(e){n.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"}),console.error(e)}finally{w(),y.reset()}}async function O(){a+=1,L();try{const r=await m(u,a);if(r.hits&&r.hits.length>0){b(r.hits);const o=B.querySelector(".gallery-item");if(o){const{height:e}=o.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}}a*d>=(r.totalHits??i)?(c(),n.info({title:"End",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):v()}catch(r){n.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"}),console.error(r)}finally{w()}}
//# sourceMappingURL=index.js.map
